// packages/captainofbass.com/src/app/links/links.component.ts
import { Component, OnInit } from '@angular/core';
import {
  faFacebookSquare,
  faInstagramSquare,
  faLinkedin,
  faMixcloud,
  faSoundcloud,
  faSpotify,
  faNapster,
  faTwitterSquare,
  faYoutubeSquare,
} from '@fortawesome/free-brands-svg-icons';

import {
  faDonate,
  faEnvelope,
  faNewspaper,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-links',
  templateUrl: './links.component.html',
  styleUrls: ['./links.component.scss'],
  animations: [],
})
export class LinksComponent implements OnInit {
  donate = faDonate;
  email = faEnvelope;
  facebook = faFacebookSquare;
  instagram = faInstagramSquare;
  linkedin = faLinkedin;
  mixcloud = faMixcloud;
  napster = faNapster;
  newspaper = faNewspaper;
  soundcloud = faSoundcloud;
  spotify = faSpotify;
  twitter = faTwitterSquare;
  youtube = faYoutubeSquare;
  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  <div class="content">
    <h1>Where to find Captain</h1>
    <hr />
    <mat-nav-list>
      <a mat-list-item [routerLink]="'/donate'">
        <fa-icon [icon]="donate"></fa-icon> Donate
      </a>
      <a
        mat-list-item
        href="http://instagram.com/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="instagram"></fa-icon> Instagram
      </a>
      <a mat-list-item href="https://twitter.com/captainofbass" target="_blank">
        <fa-icon [icon]="twitter"></fa-icon> Twitter
      </a>
      <a
        mat-list-item
        href="https://www.youtube.com/c/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="youtube"></fa-icon> Youtube
      </a>
      <a
        mat-list-item
        href="https://open.spotify.com/artist/4XHSbdpOsFpEWPOdj9nxfH"
        target="_blank"
      >
        <fa-icon [icon]="spotify"></fa-icon> Spotify
      </a>
      <a
        mat-list-item
        href="https://www.facebook.com/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="facebook"></fa-icon> Facebook
      </a>
      <a mat-list-item href="https://audius.co/captainofbass" target="_blank">
        <fa-icon [icon]="napster"></fa-icon> Audius
      </a>
      <a
        mat-list-item
        href="http://www.soundcloud.com/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="soundcloud"></fa-icon> SoundCloud
      </a>
      <a
        mat-list-item
        href="http://www.soundcloud.com/mikeallison"
        target="_blank"
      >
        <fa-icon [icon]="soundcloud"></fa-icon> SoundCloud (pre-Captain)
      </a>
      <a
        mat-list-item
        href="https://www.facebook.com/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="mixcloud"></fa-icon> MixCloud
      </a>
      <a
        mat-list-item
        href="https://www.facebook.com/mikeallison"
        target="_blank"
      >
        <fa-icon [icon]="mixcloud"></fa-icon> MixCloud (pre-Captain)
      </a>
      <a
        mat-list-item
        href="https://www.facebook.com/captainofbass"
        target="_blank"
      >
        <fa-icon [icon]="linkedin"></fa-icon> LinkedIn
      </a>
      <a mat-list-item [routerLink]="'/epk'">
        <fa-icon [icon]="newspaper"></fa-icon> Electronic Press Kit
      </a>
      <a mat-list-item href="mailto:mike@captainofbass.com" target="_blank">
        <fa-icon [icon]="email"></fa-icon> mike@captainofbass.com
      </a>
    </mat-nav-list>
  </div>
</div>

// packages/captainofbass.com/src/app/links/page.tsx
'use client'
import { faBitcoin } from '@fortawesome/free-brands-svg-icons/faBitcoin'
import { faFacebook } from '@fortawesome/free-brands-svg-icons/faFacebook'
import { faInstagram } from '@fortawesome/free-brands-svg-icons/faInstagram'
import { faLinkedin } from '@fortawesome/free-brands-svg-icons/faLinkedin'
import { faMixcloud } from '@fortawesome/free-brands-svg-icons/faMixcloud'
import { faSoundcloud } from '@fortawesome/free-brands-svg-icons/faSoundcloud'
import { faSpotify } from '@fortawesome/free-brands-svg-icons/faSpotify'
import { faXTwitter } from '@fortawesome/free-brands-svg-icons/faXTwitter'
import { faYoutube } from '@fortawesome/free-brands-svg-icons/faYoutube'
import { faEnvelope } from '@fortawesome/free-regular-svg-icons/faEnvelope'
import { faMoneyBill1 } from '@fortawesome/free-regular-svg-icons/faMoneyBill1'
import { faNewspaper } from '@fortawesome/free-regular-svg-icons/faNewspaper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Link from 'next/link'

import {
  PageContainer,
  Table,
  TableCell,
  TableRow
} from '@websites/shared/react/components'

import { GlassContainer } from '../../components/glassContainer'

export default function Music() {
  return (
    <PageContainer>
      <GlassContainer>
        <div className="text-2xl">Where to find Captain</div>
        <Table className="text-left">
          <TableRow>
            <TableCell>
              <Link href="/epk">
                <FontAwesomeIcon icon={faNewspaper} /> Electronic Press Kit
                (EPK)
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="/donate">
                <FontAwesomeIcon icon={faMoneyBill1} /> Donate (EPK)
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link
                href="https://open.spotify.com/artist/4XHSbdpOsFpEWPOdj9nxfH"
                target="_blank"
              >
                <FontAwesomeIcon icon={faSpotify} /> Spotify
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://soundcloud.com/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faSoundcloud} /> SoundCloud
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://mixcloud.com/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faMixcloud} /> MixCloud
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://mixcloud.com/mikeallison" target="_blank">
                <FontAwesomeIcon icon={faMixcloud} /> MixCloud (pre Captain)
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://audius.co/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faBitcoin} /> Audius
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://instagram.com/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faInstagram} /> Instagram
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://youtube.com/c/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faYoutube} /> Youtube
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://facebook.com/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faFacebook} /> Facebook
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="https://x.com/captainofbass" target="_blank">
                <FontAwesomeIcon icon={faXTwitter} /> X
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link
                href="https://www.linkedin.com/in/captainofbass"
                target="_blank"
              >
                <FontAwesomeIcon icon={faLinkedin} /> LinkedIn
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="mailto:mike@captainofbass.com" target="_blank">
                <FontAwesomeIcon icon={faEnvelope} /> Email
              </Link>
            </TableCell>
          </TableRow>
        </Table>
      </GlassContainer>
    </PageContainer>
  )
}
