// packages/captainofbass.com/src/app/donate/donate.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-donate',
  templateUrl: './donate.component.html',
  styleUrls: ['./donate.component.scss'],
})
export class DonateComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  <h1>Donate</h1>
  <p>Show some love and help me keep the lights on</p>
  <hr />
  <mat-nav-list>
    <a mat-list-item href="http://paypal.me/captainofbass">Paypal</a>
    <a mat-list-item href="https://venmo.com/captainofbass">Venmo</a>
    <a mat-list-item href="https://cash.app/$captainofbass">Cash App</a>
  </mat-nav-list>
</div>

// apps/captainofbass.com/src/app/donate/page.tsx
'use client'

import Link from 'next/link'

import {
  PageContainer,
  Table,
  TableCell,
  TableRow
} from '@mikeallisonjs/shared-react-components'

import { GlassContainer } from '../../components/glassContainer'

export default function Donate() {
  return (
    <PageContainer>
      <GlassContainer>
        <div className="text-2xl">
          Show some love and help me keep the lights on
        </div>
        <Table className="text-left">
          <TableRow>
            <TableCell>
              <Link href="http://paypal.me/captainofbass" target="_blank">
                Paypal
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="http://venmo.com/captainofbass" target="_blank">
                Venmo
              </Link>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Link href="http://cash.app/$captainofbass" target="_blank">
                CashApp
              </Link>
            </TableCell>
          </TableRow>
        </Table>
      </GlassContainer>
    </PageContainer>
  )
}
