// packages/captainofbass.com/src/app/epk/page.tsx
'use client'

import Link from 'next/link'

import { PageContainer } from '@mikeallisonjs/next-tailwind-shared-components/ui'

import Bio from '../../components/bio/bio'
import { GlassContainer } from '../../components/glassContainer'

export default function Epk() {
  return (
    <PageContainer>
      <Bio />
      <div className="p-1" />
      <GlassContainer>
        <div className="text-2xl">Testimonials</div>
        <div>
          &quot;Clever with a touch of amazing&quot;
          <br />- CM (Promoter)
        </div>
        <div>
          &quot;When passion and precision destroy the ideology of genres&quot;
          <br />- TM (Attendee)
        </div>
        <div>
          &quot;Untz untz womp womp&quot;
          <br />- HK (Indusry Insider & Promoter)
        </div>
        <div>
          &quot;This is like the first time I took MDMA&quot;
          <br />
          -&nbsp;(Attendee)
        </div>
      </GlassContainer>
      <div className="p-1" />
      <GlassContainer>
        <div className="text-2xl">Media</div>
        <div>
          <Link href="/assets/captain-media.zip">
            Media files (logo/pic) 1.76 MB
          </Link>
        </div>
        <div>
          <Link href="assets/captain-technical-rider.pdf">
            Technical / Performance Rider 358 KB
          </Link>
        </div>
      </GlassContainer>
      <div className="p-1" />
      <GlassContainer>
        <div className="text-2xl">Inquiries</div>
        Email:&nbsp;
        <Link href="mailto:booking@captainofbass.com">
          booking&#64;captainofbass.com
        </Link>
      </GlassContainer>
    </PageContainer>
  )
}

// packages/captainofbass.com/src/app/epk/epk.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-epk',
  templateUrl: './epk.component.html',
  styleUrls: ['./epk.component.scss']
})
export class EpkComponent {}

<div class="container">
  <img src="assets/images/narrowcap.jpg" class="photo" alt="photo of Captain" />
  <div class="overText">
    <p>"Clever with a touch of amazing"<br />- CM (Promoter)</p>
    <p>
      "When passion and precision destroy the ideology of genres"<br />- TM
      (Attendee)
    </p>
    <p>"Untz untz womp womp"<br />- HK (Indusry Insider)</p>
    <p>"This is like the first time I took MDMA"<br />-&nbsp;(Attendee)</p>
  </div>
</div>

<div class="container">
  <mat-divider></mat-divider>
  <h2>Downloads</h2>
  <p>
    <a href="assets/captain-media.zip" target="_blank"
      >Media files (logo/pic) 1.76 MB</a
    >
  </p>
  <p>
    <a href="assets/captain-technical-rider.pdf" target="_blank"
      >Technical / Performance Rider 358 KB</a
    >
  </p>
</div>

<app-bio></app-bio>

<div class="container">
  <h2>Inquiries</h2>
  <p>
    Email
    <a href="mailto:booking@captainofbass.com">booking&#64;captainofbass.com</a>
  </p>
</div>
